<?php

namespace ContainerBplumtY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuestion2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.b7bfI8K.App\Entity\Question' shared service.
     *
     * @return \App\Entity\Question
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.b7bfI8K": it references class "App\\Entity\\Question" but no such service exists.');
    }
}
