<?php

namespace ContainerRv5yPxC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YNViVOSService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YNViVOS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YNViVOS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorieRepository' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
            'quizz' => ['privates', '.errored..service_locator.YNViVOS.App\\Entity\\Categorie', NULL, 'Cannot autowire service ".service_locator.YNViVOS": it references class "App\\Entity\\Categorie" but no such service exists.'],
        ], [
            'categorieRepository' => 'App\\Repository\\CategorieRepository',
            'quizz' => 'App\\Entity\\Categorie',
        ]);
    }
}
