<?php

namespace ContainerRv5yPxC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XJndzAwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XJndzAw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XJndzAw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'reponse' => ['privates', '.errored..service_locator.XJndzAw.App\\Entity\\Reponse', NULL, 'Cannot autowire service ".service_locator.XJndzAw": it references class "App\\Entity\\Reponse" but no such service exists.'],
            'reponseRepository' => ['privates', 'App\\Repository\\ReponseRepository', 'getReponseRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'reponse' => 'App\\Entity\\Reponse',
            'reponseRepository' => 'App\\Repository\\ReponseRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
