<?php

namespace ContainerRv5yPxC;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5x_Y8bZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5x.Y8bZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5x.Y8bZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'categorie' => ['privates', '.errored..service_locator.5x.Y8bZ.App\\Entity\\Categorie', NULL, 'Cannot autowire service ".service_locator.5x.Y8bZ": it references class "App\\Entity\\Categorie" but no such service exists.'],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'categorie' => 'App\\Entity\\Categorie',
            'doctrine' => '?',
        ]);
    }
}
