<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRv5yPxC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRv5yPxC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRv5yPxC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRv5yPxC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRv5yPxC\App_KernelDevDebugContainer([
    'container.build_hash' => 'Rv5yPxC',
    'container.build_id' => '398a076f',
    'container.build_time' => 1652680106,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRv5yPxC');
